# Generated by Django 6.1.1 on 2026-09-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college_name", models.CharField(max_length=200)),
                ("college_address", models.TextField()),
                ("college_contact_number", models.CharField(max_length=20)),
                ("expiry_date", models.DateField()),
            ],
            options={
                "verbose_name": "College",
                "verbose_name_plural": "Colleges",
            },
        ),
        migrations.CreateModel(
            name="CollegeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college_name", models.CharField(max_length=200)),
                ("college_address", models.TextField()),
                ("college_contact_number", models.CharField(max_length=20)),
                ("expiry_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "College Profile",
                "verbose_name_plural": "College Profile",
            },
        ),
    ]
