# Generated by Django 6.1.1 on 2026-09-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="college_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="college",
            name="college_password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
