# Generated by Django 6.1.1 on 2026-09-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_college_college_id_college_college_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="college_image",
            field=models.ImageField(blank=True, null=True, upload_to="college_images/"),
        ),
    ]
